apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: remote-cluster-sep29-8 
  description: Secure Supply Chain Example for Object Detection Application   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=remote-cluster-sep29-8  
    janus-idp.io/tekton: remote-cluster-sep29-8 
    backstage.io/kubernetes-id: remote-cluster-sep29-8 
    backstage.io/techdocs-ref: dir:. 
    quay.io/repository-slug: rh-ee-lyoon-dh/remote-cluster-sep29-8
  tags: ["ai", "detr", "python"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 